services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: setup
    ports:
      - "8000:8000"
    volumes:
      - .:/docs
    working_dir: /docs
    command: serve -a 0.0.0.0:8000
