site_name: Help Desk
site_url: https://help.xeroxdev.de
repo_url: https://github.com/XeroxDev/help.xeroxdev.de
repo_name: Docs Source Code
edit_uri: edit/main/docs/
site_author: XeroxDev
site_description: 'Help Desk for all my projects'
theme:
  name: material
  language: en
  logo: assets/images/logo.png
  favicon: assets/images/logo.png
  palette:
    scheme: slate
    primary: custom
    accent: custom
  features:
    - navigation.tracking
    - navigation.sections
    - navigation.indexes
    - toc.follows
    - navigation.top
    - search.suggest
    - content.action.edit
    - content.code.copy
    - content.code.annotate
    - content.tooltips
plugins:
  - privacy
  - search
  - awesome-nav
  - social
  - glightbox
  - macros
  - redirects:
      redirect_maps:
        en/loupedeck/elgato-control/home.md: en/loupedeck/elgato-control/index.md
        en/loupedeck/nanoleaf-control/home.md: en/loupedeck/nanoleaf-control/index.md
        en/loupedeck/speedtest/home.md: en/loupedeck/speedtest/index.md
        en/loupedeck/streamerbot/home.md: en/loupedeck/streamerbot/index.md
        en/loupedeck/voicemeeter/home.md: en/loupedeck/voicemeeter/index.md
        en/loupedeck/ytmd/home.md: en/loupedeck/ytmd/index.md
        en/stream-deck/ytmd/home.md: en/stream-deck/ytmd/index.md
  - minify:
      minify_html: true
extra_css:
  - assets/stylesheets/extra.css
extra_javascript:
  - https://cdn.tailwindcss.com
  - assets/javascripts/extra.js
copyright: 'Copyright &copy; 2021 - <script>document.write(new Date().getFullYear())</script> | Written with <span class="twemoji" style="color: #CC2255"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="m12 21.35-1.45-1.32C5.4 15.36 2 12.27 2 8.5 2 5.41 4.42 3 7.5 3c1.74 0 3.41.81 4.5 2.08C13.09 3.81 14.76 3 16.5 3 19.58 3 22 5.41 22 8.5c0 3.77-3.4 6.86-8.55 11.53z"></path></svg></span> by XeroxDev'
markdown_extensions:
  - toc:
      permalink: true
      title: On this page
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - pymdownx.betterem
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      base_path:
        - docs
        - snippets
      check_paths: true
      auto_append:
        - _refs.md
        - _abbr.md
      restrict_base_path: true
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      auto_title: true
      linenums: true
      linenums_style: pymdownx-inline
      line_spans: __span
      pygments_lang_class: true
draft_docs: |
  draft/
  .*
hooks:
  - hooks/link-rewrite.py
watch:
  - main.py
  - snippets/
validation:
  links:
    absolute_links: relative_to_docs
